### ISSUE TITLE
Comparison of this with OllyDbg's original "Paperback"

### ISSUE THREAD

**Issue by DonaldTsang** [matheusd/pypaperbak#1]
Would like to know if this software can store as much data as OllyDbg's verison.
https://github.com/timwaters/paperback
https://github.com/Wikinaut/paperback-cli

**Comment by matheusd** [comment]
IIIRC, it OllyDbg's version uses a custom raw binary format vs my version which uses QR codes.

They can achieve greater density a the cost of using less standard formats for encoding the data.

**Comment by DonaldTsang** [comment]
@matheusd please mark the differences on the ReadME if you can.
